apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask
          image: 800802900236.dkr.ecr.us-east-1.amazonaws.com/inventory:flask-latest
          ports:
            - containerPort: 5000
          env:
            - name: API_URL
              valueFrom:
                secretKeyRef:
                  name: pod-secret
                  key: API_URL

            
        
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer